JOKES = [
    "I went to a street where the houses were numbered 8k, 16k, 32k, 64k, 128k, 256k and 512k.\nIt was a trip down Memory Lane.",
    "If doctors were like software engineers, they would say things like “Have you tried killing yourself and being reborn?”",
    "“Debugging” is like being the detective in a crime drama where you are also the murderer.",
    "!false\n(It’s funny because it’s true.)",
    "Why do programmers always mix up Christmas and Halloween?\nBecause Dec 25 is Oct 31.",
    "The best thing about a Boolean is that even if you are wrong, you are only off by a bit.",
    "An SQL query goes into a bar, walks up to two tables and asks: “Can I join you?”",
    "Programming is like sex. One mistake and you have to support it for the rest of your life.",
    "If you listen to a UNIX shell, can you hear the C?",
    "Why do Java programmers have to wear glasses?\nBecause they don’t C#.",
    "What did the router say to the doctor?\n“It hurts when IP”",
    "When Apple employees die, does their life HTML5 in front of their eyes?",
    "How did the programmer die in the shower? A. He read the shampoo bottle instructions: Lather. Rinse. Repeat.",
    "How many programmers does it take to change a light bulb? None – It’s a hardware problem",
    "When I wrote this code, only me and God knew how it works. Now only God knows…",
    "Give a man a program, and frustrate him for a day. Teach a man to program, frustrate him for a lifetime.",
    "What did Java code call a C code? You have no class.",
    "Why did the programmer quit his job? Because he didn’t get any arrays[raise]",
    "Why was the DBA divorced? Because the DBA has one to many relationships.",
    "If you put a million monkeys at a million keyboards, one of them will eventually write a Java program. The rest of them will write C# programs.",
    " Software undergoes beta testing shortly before it’s released. Beta is Latin for ‘still doesn’t work. Sources",
    "Why don't programmers like nature? It has too many bugs.",
    "Why was the JavaScript developer sad? Because he didn't know how to 'null' his feelings.",
    "Why did the developer go broke? Because he used up all his cache.",
    "Why don't programmers like to play hide and seek? Because good players are hard to find.",
    "Why did the developer go to therapy? Because he had too many sessions with his database.",
    "Why was the developer unhappy at his job? He wanted arrays of sunshine in his life, but all he got was a case of the Mondays.",
    "Why was the Python developer so stressed out? Because he didn't know how to 'return' home!",
    "Why do Python programmers prefer to use spaces over tabs? Because they can't stand indents.",
    "Why was the Python programmer not good at football? Because he kept getting a syntax error when he tried to 'kick' the ball.",
    "Why did the Python programmer go broke? Because he used up all his 'cache'!",
    "Why was the Python developer always so calm? Because he never got into an 'exceptional' situation.",
    "Why did the Python developer get lost? Because he couldn't find his 'py'!",
    "Why did the Python programmer always carry a ladder? Because he heard the Python language was on a higher level.",
    "Why do Python programmers prefer tea over coffee? Because they prefer 'T' over 'C'.",
    "Why did the CSS file break up with the HTML file? It caught it cheating with JavaScript!",
    "Why did the CSS developer go to therapy? Because he had too many 'class' issues!",
    "Why did the CSS file go to jail? Because it had too many 'selectors'!",
    "Why don't programmers like nature? It has too many 'bugs'.",
    "Why did the CSS file become a DJ? Because it knew how to 'style' the beats!",
    "Why was the JavaScript developer sad? Because he didn't know how to 'null' his feelings.",
    "Why did the developer go broke? Because he used up all his cache.",
    "Why do C++ programmers prefer to use smart pointers? Because they don't like to lose their memory!",
    "Why did the C++ code get glasses? It couldn't C#",
    "Why don't C++ developers get Christmas and Halloween mixed up? Because Dec 25 is Dec 31!",
    "Why don't C++ developers like nature? It has too many bugs!",
    "Why did the C++ developer go broke? Because he used up all his cache!",
    "Why did the C++ code fail to win the race? It was always stuck in the void!",
    "Why did the C++ developer get stuck in the shower? Because he couldn't find the soap!",
    "Why was the C++ developer always calm? Because he never got into an 'exceptional' situation!",
    "Why did the C++ developer go to therapy? Because he had too many 'pointers' to deal with!",
    "Why did the C++ developer refuse to get a job? He didn't want to inherit any 'classes'!",
    "Why did the C++ developer always carry a ladder? Because he heard the C++ language was on a higher level!",
    "Why did the C++ developer go broke? Because he used up all his 'exceptions'!",
    "Why was the C++ developer sad? Because he couldn't 'nullptr' his feelings!",
]
